### ISSUE TITLE
Blank screen when starting webcatalog

### ISSUE THREAD

**Issue by nyex** [quanglam2807/appifier#246]
I'm now with 9.2.0. WebCatalog loads for a few seconds during which I can see the main page, but then it's gone. The apps themselves (say, the Gmail app etc) load fine.

It actually started BEFORE I updated to 9.2.0, which is very strange. I renamed all webcatalog's related folders in my user's folder, but the problem persisted. Then I tried purging and reinstalling the program... still nothing.

![captura de tela de 2018-01-12 19-54-16](https://user-images.githubusercontent.com/15344684/34898810-bd305544-f7d3-11e7-986d-07bffb2921d0.png)

If I click the debug option, it shows one error:

```
TypeError: Invalid Version: undefined
    at new i (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:61471)
    at h (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:62894)
    at Function.b [as gt] (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:63158)
    at d (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:31055)
    at file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:31166
    at Array.forEach (native)
    at p (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:31146)
    at Function.L [as mapToProps] (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:541434)
    at r (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:104651)
    at s (file:///opt/WebCatalog/resources/app/build/static/js/main.c770fe04.js:1:275425)
s @ react-dom.production.min.js:164
```

I'm on Ubuntu 17.10 64bit. WebCatalog version is 9.2.0, but it happened first on 9.1.2, which had worked fine before.

**Comment by quanglam2807** [comment]
This is terrible. It also happens on my Mac. I no longer use the app daily so bug like this occurs. I'll try to fix it ASAP.

<img width="1093" alt="screen shot 2018-01-12 at 5 59 42 pm" src="https://user-images.githubusercontent.com/1548835/34900047-6244908e-f7c2-11e7-9106-d21b815720d5.png">

**Comment by quanglam2807** [comment]
Backend bug. :)
