### ISSUE TITLE
Cann‘t build a deb

### ISSUE THREAD

**Issue by sikenali** [quanglam2807/appifier#261]
electron-installer-debian --src /home/jingle/Desktop/Wechat-linux-x64/ --dest /home/jingle/Desktop/wechat/ --arch amd64
Creating package (this may take a while)
Error: No Description or ProductDescription provided
    at getOptions (/usr/lib/node_modules/electron-installer-debian/src/installer.js:149:11)
    at getDefaults.then.defaults (/usr/lib/node_modules/electron-installer-debian/src/installer.js:418:23) 'Error: No Description or ProductDescription provided\n    at getOptions (/usr/lib/node_modules/electron-installer-debian/src/installer.js:149:11)\n    at getDefaults.then.defaults (/usr/lib/node_modules/electron-installer-debian/src/installer.js:418:23)'

**Comment by sikenali** [comment]
I create form https://github.com/quanglam2807/appifier


you create file  /home/jingle/Desktop/Wechat-linux-x64/resources/app.asar.unpacked/package.json

no description argument

I added it  ok

**Comment by jingle0927** [comment]
electron version too lower?

**Comment by quanglam2807** [comment]
@jingle0927 If you can make a PR, that'd be nice :)

**Comment by quanglam2807** [comment]
Appifier GUI has been deprecated. Please wait for the first release of https://github.com/quanglam2807/webcatalog-lite
